name: seq_sim_pred_ml
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - pyarrow
  - numpy>=2.0.0
  - pandas
  - pytorch==2.4.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - conda-forge::lightning
  - matplotlib
  - scikit-learn==1.5.2
  - seaborn
  - pytest
  - pip
  - pip:
    - lightning[extra]
    - tensorboard
  