name: laura_genome
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - biopython>=1.81
  - muscle>=5.1
  - ete3>=3.1
  # WGS pipeline tools
  - quast>=5.2
  - checkm2>=1.0
  - prokka>=1.14
  - abricate>=1.0
  - mlst>=2.0
